"""followers

Revision ID: 187f4d04e1f1
Revises: 9503bb4d5679
Create Date: 2021-09-20 17:03:12.318085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187f4d04e1f1'
down_revision = '9503bb4d5679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
